---
title: "Leslie Matrix Practice"
format: html
editor: visual
---

## Matrixes

```{r}
# Make a sequence of vlaues from 1 to 10
my_values <- seq(from = 1, to = 10, by = 1)

#look at values

my_values
```
```{r}
# Convert to matrix

my_matrix <- matrix(data = my_values,
                    nrows = 2,
                    ncol = 5, byrow = TRUE)
my_matrix
```


```{r}
matrix(data = my_values,
nrow = 3,
ncol = 4, byrow = TRUE)
```
## Matrix Math

```{r}
4 * my_matrix
```
```{r}
my_values2 <- seq(from = 21, to = 30)
my_matrix2 <- matrix(my_values2, nrow = 2, byrow = TRUE)
my_matrix2
```
```{r}
my_matrix + my_matrix2
```
### Matrix Multiplication

# make a couple of 2x2 matrices
```{r}
cats <- matrix(data = c(0,4,3,1, nrow = 2, byrow = TRUE))
dogs <- matrix(data = c(6,-3,0,2), nrow= 2, byrow = TRUE)

cats
dogs
```

```{r}
# multi matrix
cats %*% dogs
```

## Leslie matrix ex
```{r}

#Create Matrix 
insect_leslie <- matrix(c(0,0,600,0.02,0,0,0,0.8,0),
                        nrow = 3,
                        ncol = 3,
                        byrow = TRUE)
insect_leslie
```

Specify initial conditions

```{r}
#insect lifestage pop size (year 0)
insect_y0 <- c(1200,700,500)
```
Find pop for each lifestages at year 1

```{r}
insect_y1 <- insect_leslie %*% insect_y0
insect_y1
```
Find pop at year 2
```{r}
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
```
```{r}
insect_y3 <- insect_leslie %*% insect_y2
insect_y3
```
##  Another section

```{r}
# make project matrix

tree_leslie <- matrix(c(0,0,5000,.1,0,0,0,0.06,0.95),
                      nrow = 3,
                      ncol = 3,
                      byrow = TRUE)
tree_leslie
```
#create conditions for year 0
```{r}
tree_0 <-c(5000,0,0)
```

# year 1
```{r}
tree_1 <- tree_leslie %*% tree_0
tree_1

#year 2
tree_2 <- tree_leslie %*% tree_1
tree_2

#year 3
tree_3 <- tree_leslie %*% tree_2
tree_3

tree_4 <- tree_leslie %*% tree_3
tree_4

```















